### ISSUE TITLE
offset the text when there is autocompletion

### ISSUE THREAD

**Issue by akabakass** [Dan7h3x/signup.nvim#3]
Hi, nice plugin, but it shows behind the autocomplete section
![image](https://github.com/user-attachments/assets/694d57ad-39bf-443a-9937-75544258f008)
I'm using nvim-cmp,
Please tell me if you need anything else

**Comment by Dan7h3x** [comment]
Hi 

> Hi, nice plugin, but it shows behind the autocomplete section ![image](https://private-user-images.githubusercontent.com/10631421/376273998-694d57ad-39bf-443a-9937-75544258f008.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDk5MTcsIm5iZiI6MTcyOTYwOTYxNywicGF0aCI6Ii8xMDYzMTQyMS8zNzYyNzM5OTgtNjk0ZDU3YWQtMzliZi00NDNhLTk5MzctNzU1NDQyNThmMDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE1MDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNzU5ZjFiMGUyNThlMTY3MjFiMWZjMWMyZTg2NjM2ODhkN2IwNTAwODEzMjYyZmU5OTQ0ZjUxNDU3MzM4MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uyxl4h7wbh65JB81Fhf_da7_NZ-EJU1S902uuxGJScs) I'm using nvim-cmp, Please tell me if you need anything else

Hi buddy, i was busy for weeks until now, and some good updates gonna i work on, if you want please contribute on this plugin. Thanks

**Comment by Dan7h3x** [comment]
> Hi, nice plugin, but it shows behind the autocomplete section ![image](https://private-user-images.githubusercontent.com/10631421/376273998-694d57ad-39bf-443a-9937-75544258f008.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMTQxNjgsIm5iZiI6MTczMjIxMzg2OCwicGF0aCI6Ii8xMDYzMTQyMS8zNzYyNzM5OTgtNjk0ZDU3YWQtMzliZi00NDNhLTk5MzctNzU1NDQyNThmMDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE4MzEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YTkwZTA5N2Q4M2E2ZDAzNWJmYjZjOWUyMjdmMTEzMzc0ZmIwNjYzODUzOWU5YTQ0MjQ0YTQ4YTA1OTUzMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uNMIVtzAE9Y5JiMTMPubTECe7KX_22jhcVsXLOBRCTg) I'm using nvim-cmp, Please tell me if you need anything else

I fixed the problem, just update your neovim plugins
