### ISSUE TITLE
Failed to run `config` for signup.nvim

### ISSUE THREAD

**Issue by andysazima** [Dan7h3x/signup.nvim#4]
Neovim shoots me this error when I start up a new session with this plugin added.

```
2024-11-25T10:23:01 lazy.nvim  ERROR  | lazy.nvim: Failed to run `config` for signup.nvim

...1/.local/share/nvim/lazy/signup.nvim/lua/signup/init.lua:389: attempt to index field 'config' (a nil value)
```

Tell me if I'm wrong, but when I look at the source code (line 389), it seems that you have mistakenly put `opts.config...` for fg and bg instead of `signature_help.config`. This would explain the "nil value" of the table.

When I manually change that table to what I suggested, the plugin works!

**Comment by andysazima** [comment]
I understand that this would not allow for any new settings to be input. Maybe the `opts` variable should be assigned the default config table, then it gets overwritten by the user when require...setup is called?

The solution I'm using now is just specifying the fg and bg in config.

Another issue I'm running into is that "silent" isn't working. I decided to just edit "init.lua" in my installed copy to remedy this, but I haven't taken a look to see why.

**Comment by Dan7h3x** [comment]
> Neovim shoots me this error when I start up a new session with this plugin added.
> 
> ```
> 2024-11-25T10:23:01 lazy.nvim  ERROR  | lazy.nvim: Failed to run `config` for signup.nvim
> 
> ...1/.local/share/nvim/lazy/signup.nvim/lua/signup/init.lua:389: attempt to index field 'config' (a nil value)
> ```
> 
> Tell me if I'm wrong, but when I look at the source code (line 389), it seems that you have mistakenly put `opts.config...` for fg and bg instead of `signature_help.config`. This would explain the "nil value" of the table.
> 
> When I manually change that table to what I suggested, the plugin works!

Thanks for reporting
I fixed that and updated the plugin, just read readme for more.

**Comment by Dan7h3x** [comment]
> I understand that this would not allow for any new settings to be input. Maybe the `opts` variable should be assigned the default config table, then it gets overwritten by the user when require...setup is called?
> 
> The solution I'm using now is just specifying the fg and bg in config.
> 
> Another issue I'm running into is that "silent" isn't working. I decided to just edit "init.lua" in my installed copy to remedy this, but I haven't taken a look to see why.

yeah these two now works well
